name: mental_health_app
description: A comprehensive mental health support app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  provider: ^6.0.5
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.1
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  http: ^1.1.0
  flutter_local_notifications: ^15.1.1
  url_launcher: ^6.1.14
  dialogflow_flutter: ^1.0.0
  lottie: ^2.6.0
  audioplayers: ^5.1.0
  table_calendar: ^3.0.9
  cached_network_image: ^3.2.3
  flutter_markdown: ^0.6.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300